# Simple set of rules for GitHub actions integration with a ROS project
#

name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.19
        with:
          required-ros-distributions: jazzy
      - name: Install dependencies
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: sicks300_ros2
          target-ros2-distro: jazzy
          skip-tests: false
